# Generated by Django 4.2.6 on 2023-10-26 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0002_day_shift_employee_schedule_work_shift_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Day_Shift',
            new_name='DayShift',
        ),
    ]
