# Generated by Django 4.2.6 on 2023-11-02 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling_app', '0003_rename_day_shift_dayshift'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Work_Shift',
            new_name='WorkShift',
        ),
    ]
